apps:
  hwview:
    command: 'usr/bin/hwview'
    common-id: 'sh.tat.hwview'
    desktop: 'usr/share/applications/sh.tat.hwview.desktop'
    extensions:
      - 'kde-neon-6'
    plugs:
      - 'desktop'
      - 'desktop-legacy'
      - 'hardware-observe'
      - 'home'
      - 'opengl'
      - 'system-observe'
      - 'wayland'
      - 'x11'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/hwview/issues'
description: |
  Hardware Viewer is a cross-platform hardware information utility inspired by
  Redmond. It shows devices, drivers, and system resources in multiple
  hierarchical and categorised views, with detailed device properties and
  optional export of the collected information.
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/hwview/issues'
license: 'MIT'
name: 'hwview'
parts:
  hwview:
    build-environment:
      - LDFLAGS: '-Wl,--allow-shlib-undefined'
    build-packages:
      - 'extra-cmake-modules'
      - 'libudev-dev'
    build-snaps:
      - 'cmake/latest/stable'
    cmake-parameters:
      - '-DCMAKE_BUILD_TYPE=Release'
      - '-DCMAKE_INSTALL_PREFIX=/usr'
      - '-DFHS=ON'
    plugin: 'cmake'
    source: '.'
    stage-packages:
      - 'libudev1'
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/hwview'
summary: 'Hardware information utility'
title: 'Hardware Viewer'
version: '0.0.2'
website: 'https://github.com/Tatsh/hwview'
